name: Create Artifacts
on: [push, workflow_dispatch]

jobs:
    test:
        name: Test Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - name: Install Dependencies
              run: bun install
            - name: Run with different seeds
              run: |
                bun run random-number-generator.js
                bun run random-number-generator.js "test-seed"
                bun run random-number-generator.js 1906
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: report.txt
    build:
        name: Build Code
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup
              uses: oven-sh/setup-bun@v2
            - name: Install Dependencies
              run: bun install
            - name: Create Executables
              run: bun run build
            - name: List Executables
              run: ls -la random-number-generator-*
            - name: Create Artifact
              uses: actions/upload-artifact@v4
              with:
                name: random-number-generator-executables
                path: ./random-number-generator-*

    test-linux:
        name: Test Linux Executable
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: random-number-generator-executables
            - name: Make linux binary executable
              run: chmod +x random-number-generator-linux
            - name: Install Dependencies
              run: bun install
            - name: multi line commands
              run: |
                ./random-number-generator-linux
                ./random-number-generator-linux "test-seed"
                ./random-number-generator-linux 1906
            - name: Upload Report
              uses: actions/upload-artifact@v4
              with:
                name: linux-test-report
                path: report.txt



